# Generated by Django 2.1.4 on 2020-03-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=128, unique=True)),
                ('hash_code', models.CharField(max_length=128)),
                ('d_hamming', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['d_hamming'],
            },
        ),
    ]
