# Generated by Django 2.1.4 on 2020-03-27 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='d_hamming',
        ),
        migrations.AddField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload time'),
            preserve_default=False,
        ),
    ]
